<a href="https://colab.research.google.com/github/ArchanaSahoo89/Numpy_Assignment/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Theoretical Questions & Answers:

In [ ]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


# Here’s why NumPy is used widely in python for scientific computing and data analysis:

# Speed and Efficiency: NumPy is designed for performance. It uses optimized C and Fortran libraries under the hood, so numerical operations are super fast.

# Array Operations: Handling large, multi-dimensional arrays is a breeze with NumPy. Think of it as Excel on steroids.

# Mathematical Functions: It’s packed with mathematical functions: everything from basic arithmetic to advanced algebraic operations. No need to reinvent the wheel.

# Integration: NumPy works seamlessly with other Python libraries like SciPy, pandas, and matplotlib, creating a powerhouse for data analysis and visualization.

# In essence, NumPy supercharges Python, making it a formidable tool for anything number-crunching related.


In [ ]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


# np.mean() is a function that calculates the arithmetic mean along the specified axis or across the entire array if no axis is specified. It’s simple, fast, and usually what you want when we are dealing with a basic dataset.

# np.average() is a bit more versatile. Besides calculating the mean, it also allows for weighting of elements. we can specify weights, and the function will compute a weighted average. This can be especially useful when it is needed to account for varying importance or frequency of elements in your dataset.

# we can use np.mean() for standard, unweighted averages. np.average() comes in handy when dealing with datasets where some values should be weighted more heavily than others.



In [ ]:
# 3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.


# Reversing a NumPy array can be accomplished using various methods depending on whether we want to reverse along different axes.Below are some common methods to reverse both 1D and 2D NumPy arrays.

# 1D Array Reversal

# For a 1D array, we can reverse it using slicing.
# Example:

import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print("Original 1D Array:", arr_1d)
print("Reversed 1D Array:", reversed_arr_1d)

# 2D Array Reversal

# For a 2D array, we can reverse along specific axes using slicing.
# Example:

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse along the first axis (rows)
reversed_rows = arr_2d[::-1, :]

print("Original 2D Array:\n", arr_2d)
print("Reversed along first axis (rows):\n", reversed_rows)

# Reverse along the second axis (columns)
reversed_columns = arr_2d[:, ::-1]

print("Reversed along second axis (columns):\n", reversed_columns)

# These methods are efficient and take advantage of NumPy's slicing capabilities to quickly reverse arrays.



Original 1D Array: [1 2 3 4 5]
Reversed 1D Array: [5 4 3 2 1]
Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along first axis (rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along second axis (columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

# we can determine the data type of elements in a NumPy array using the .dtype attribute. This attribute returns a NumPy data type object that describes the type of the array's elements.

# Example:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
data_type = arr.dtype
print("Data type of the array:", data_type)

# Importance of Data Types in Memory Management and Performance

# Memory Efficiency:
# Different data types require different amounts of memory. For instance, int32 uses 4 bytes, while int64 uses 8 bytes. Choosing the appropriate data type can significantly reduce memory usage, especially with large datasets.
# When working with large arrays, using smaller data types (like float32 instead of float64, or int8 instead of int64) can lead to substantial memory savings.

# Performance:
# Operations on arrays can be faster with certain data types. For example, computations with float32 might be quicker than float64 on some hardware due to lower data size.
# The choice of data type can also affect the performance of NumPy's underlying operations. For instance, vectorized operations might be optimized for specific data types.

# Precision and Range:
# Choosing the right data type affects both the precision and the range of values that can be represented. For example, using int8 limits values between -128 and 127, which might lead to overflow issues if not properly managed.
# Using floating-point numbers can introduce precision issues, so it’s essential to choose a type that balances range and precision for the specific application.

# Type Compatibility:
# When performing operations on arrays of different data types, NumPy will attempt to cast types to a common type (which may result in loss of information). Understanding the data types helps prevent unexpected behaviors during calculations.

# Choosing the right data type can lead to more efficient code and prevent potential errors related to overflow or loss of precision.


Data type of the array: int64


In [ ]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?


# In NumPy, an ndarray (N-dimensional array) is a powerful data structure used for storing and manipulating large datasets in a multidimensional format. Here are the key features of ndarrays and how they differ from standard Python lists:

# Key Features of ndarrays:

# Homogeneous Data Type:
# All elements in a NumPy array are of the same data type (e.g., all integers, all floats). This allows for more efficient storage and computation.

# Multidimensional:
# ndarrays can have multiple dimensions (1D, 2D, 3D, etc.), allowing for complex data structures such as matrices, tensors, and higher-dimensional data.

# Fixed Size:
# The size of a NumPy array is fixed upon creation. If you need a different size, you must create a new array.

# Efficient Memory Usage:
# ndarrays are more memory-efficient compared to Python lists due to their homogeneous nature and contiguous memory storage.

# Vectorized Operations:
# NumPy supports element-wise operations, allowing you to perform mathematical operations on entire arrays without the need for explicit loops. This leads to cleaner code and significantly improved performance.

# Broadcasting:
# NumPy can automatically expand the dimensions of arrays during arithmetic operations to make them compatible, which simplifies calculations involving arrays of different shapes.

# Rich Functionality:
# NumPy provides a vast library of mathematical functions, statistical operations, and linear algebra routines that operate directly on ndarrays.

# Interoperability:
# NumPy arrays are often used with other scientific computing libraries (like SciPy, Pandas, and Matplotlib), making them a cornerstone of scientific computing in Python.


# Differences from Standard Python Lists:

# Data Type:
# Python lists can store elements of different data types (e.g., integers, strings, lists, etc.), while NumPy arrays require all elements to be of the same type.

# Performance:
# NumPy arrays are generally faster for numerical computations due to their optimized C backend and the ability to perform operations in bulk (vectorization). Python lists are slower for numerical operations because they require explicit loops.

# Memory Efficiency:
# NumPy arrays use less memory than Python lists. Lists require additional memory overhead to store type information for each element, while ndarrays store elements in a contiguous block of memory.

# Functionality:
# NumPy arrays come with built-in mathematical functions and capabilities that Python lists lack. Operations on lists often require manual iteration or additional libraries.

# Size and Resizing:
# The size of a NumPy array is fixed once created, whereas Python lists can be dynamically resized (elements can be added or removed).


# Example:

import numpy as np
py_list = [1, 2, 3, 4]
np_array = np.array([1, 2, 3, 4])
py_list.append(5)
np_array = np.append(np_array, 5)
np_squared = np_array ** 2
print("Python List:", py_list)
print("NumPy Array:", np_array)
print("Squared NumPy Array:", np_squared)

# ndarrays are a powerful alternative to standard Python lists, especially for numerical and scientific computing, due to their efficiency, functionality, and ease of use with mathematical operations.


Python List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]
Squared NumPy Array: [ 1  4  9 16 25]


In [ ]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

# NumPy arrays provide significant performance benefits over Python lists, particularly for large-scale numerical operations.

# I. Memory Efficiency
# Contiguous Memory Allocation: NumPy arrays are stored in contiguous memory locations, allowing for better cache coherence. This reduces the time needed to access data compared to Python lists, which store references to objects that may be scattered in memory.
# Homogeneous Data Types: NumPy arrays require all elements to be of the same data type, which allows for more compact storage. In contrast, Python lists can contain mixed types, resulting in additional overhead for storing type information.

# II. Performance and Speed
# Vectorized Operations: NumPy allows operations to be performed on entire arrays without explicit loops. This is achieved through vectorization, which translates high-level operations into optimized C code, resulting in substantial speed improvements.
# Ex:
import numpy as np

arr = np.arange(1_000_000)
result = arr * 2

# Reduction of Python Overhead: When using Python lists, operations often involve a lot of Python-level overhead due to the interpreted nature of the language. NumPy minimizes this overhead by leveraging compiled code, resulting in faster execution times.

# III. Broadcasting Capabilities

# Automatic Expansion: NumPy supports broadcasting, allowing arrays of different shapes to be used in arithmetic operations without needing to manually align their shapes. This feature simplifies coding and enhances performance.
#Example:

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
result = a + b

# IV. Built-in Functions

# Optimized Mathematical Functions: NumPy includes a vast array of optimized mathematical functions, such as np.sum(), np.mean(), and more, which are implemented in C. These functions are typically faster than equivalent Python list operations, especially for large datasets.

# V. Parallelism and Efficiency

#Multi-threading and SIMD: NumPy can leverage multi-threading and SIMD (Single Instruction, Multiple Data) capabilities of modern CPUs for parallel processing. This leads to significant performance gains, especially for large-scale computations.

# VI. Lower Overhead for Large Data Sets
#Reduced Function Call Overhead: Operations on large datasets in Python incur overhead due to repeated function calls. In contrast, NumPy processes large chunks of data at once, reducing the overhead and speeding up calculations.

#Performance Comparison Example:

import numpy as np
import time

size = 10_000_000
list_a = list(range(size))
list_b = list(range(size))

start_time = time.time()
list_result = [x + y for x, y in zip(list_a, list_b)]
print("Python List Time:", time.time() - start_time)

array_a = np.array(list_a)
array_b = np.array(list_b)

start_time = time.time()
array_result = array_a + array_b
print("NumPy Array Time:", time.time() - start_time)

# These advantages make NumPy a powerful tool for numerical computing, data analysis, and scientific research, especially when handling large datasets.


Python List Time: 1.003739833831787
NumPy Array Time: 0.04016828536987305


In [ ]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

# In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. Here’s a comparison of both functions along with examples demonstrating their usage.

# vstack()

# Function: numpy.vstack(tup)
# Description: Stacks arrays in sequence vertically (row-wise). This means it adds rows on top of each other.
# Input: A tuple of arrays that have the same shape along all but the first axis.

# Example of vstack():

import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

result_vstack = np.vstack((array1, array2))

print("Result of vstack:")
print(result_vstack)

# hstack()

# Function: numpy.hstack(tup)
# Description: Stacks arrays in sequence horizontally (column-wise). This means it adds columns side by side.
# Input: A tuple of arrays that have the same shape along all but the second axis.

# Example of hstack()

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

result_hstack = np.hstack((array1, array2))

print("\nResult of hstack:")
print(result_hstack)

# Both vstack() and hstack() are useful for combining arrays, but they serve different purposes depending on how you want to organize your data. we can use vstack() when we want to stack arrays row-wise and hstack() when we want to stack them column-wise.


Result of vstack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result of hstack:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

# In NumPy, the fliplr() and flipud() functions are used to flip arrays along specific axes. Here’s a detailed explanation of both methods, including their differences and effects on various array dimensions.

# 1. fliplr()

# Function: numpy.fliplr(m)
# Description: Flips an array from left to right (horizontally).
# Input: A 2D array.
# Effect: Each row of the array is reversed, which means the first column becomes the last, the second column becomes the second-to-last, and so on.

# Example:

import numpy as np

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

flipped_lr = np.fliplr(array_2d)

print("Original Array:")
print(array_2d)

print("\nFlipped Left to Right (fliplr):")
print(flipped_lr)

# 2. flipud()

# Function: numpy.flipud(m)
# Description: Flips an array up to down (vertically).
# Input: A 2D array.
# Effect: Each column of the array is reversed, which means the first row becomes the last, the second row becomes the second-to-last, and so on.
# Example of flipud()

flipped_ud = np.flipud(array_2d)

print("\nFlipped Up to Down (flipud):")
print(flipped_ud)

# Effects on Various Array Dimensions

# 1D Arrays: Both fliplr() and flipud() do not apply to 1D arrays since they are designed for 2D arrays. Using them on a 1D array will result in an error.

# 2D Arrays: As demonstrated, both functions operate on the last two dimensions of the array, allowing for flipping either horizontally or vertically.

# 3D Arrays and Higher: For arrays with more than two dimensions, fliplr() and flipud() will only apply to the last two dimensions. The remaining dimensions will remain unchanged. This can be useful when dealing with multi-dimensional datasets.


# fliplr() and flipud() are useful functions for flipping 2D arrays horizontally and vertically, respectively. They are designed specifically for 2D arrays and do not have meaningful effects on 1D arrays, while they can also operate on the last two dimensions of higher-dimensional arrays. Understanding these functions is crucial for manipulating data in NumPy effectively.



Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Left to Right (fliplr):
[[3 2 1]
 [6 5 4]
 [9 8 7]]

Flipped Up to Down (flipud):
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [1]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

# The array_split() method in NumPy is used to split an array into multiple sub-arrays. Unlike split(), which requires the splits to be equal, array_split() can handle uneven splits. Here’s a detailed overview of its functionality and behavior, especially regarding uneven splits.

# Functionality of array_split():

# Function Signature: numpy.array_split(ary, indices_or_sections, axis=0)
# Parameters:
# ary: The input array to be split.
# indices_or_sections: This can be an integer specifying the number of equal sections to divide the array into or an array of indices at which to split.
# axis: The axis along which to split the array. The default is 0 (rows for 2D arrays).

# Key Features:

# Handling Uneven Splits:
# If the array cannot be split evenly (for example, if you try to split an array of size 10 into 3 parts), array_split() will create sub-arrays that may have different shapes. Specifically, it will distribute the leftover elements across the first few sub-arrays.
# Returning a List:
# The function returns a list of sub-arrays resulting from the split. The length of this list is determined by the specified number of sections or indices.

# Example Usage

# Even Split

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

split_arrays = np.array_split(array, 5)

print("Even Split Result:")
for idx, sub_array in enumerate(split_arrays):
    print(f"Sub-array {idx+1}: {sub_array}")

# Uneven Split

uneven_split_arrays = np.array_split(array, 3)

print("\nUneven Split Result:")
for idx, sub_array in enumerate(uneven_split_arrays):
    print(f"Sub-array {idx+1}: {sub_array}")

# Explanation of Uneven Splits:

# In the example above, splitting the array of size 10 into 3 parts resulted in:
# The first sub-array contained 3 elements.
# The second sub-array contained 2 elements.
# The last sub-array contained the remaining 5 elements.
# This demonstrates how array_split() distributes the leftover elements across the resulting sub-arrays when the splits are uneven.

# array_split() is an essential function for efficiently dividing arrays, particularly in scenarios where the dataset size may not evenly divide into the desired number of sections.


Even Split Result:
Sub-array 1: [1 2]
Sub-array 2: [3 4]
Sub-array 3: [5 6]
Sub-array 4: [7 8]
Sub-array 5: [ 9 10]

Uneven Split Result:
Sub-array 1: [1 2 3 4]
Sub-array 2: [5 6 7]
Sub-array 3: [ 8  9 10]


In [ ]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

# Vectorization and broadcasting are two powerful features in NumPy that significantly enhance the efficiency of array operations.

# Vectorization:

# Vectorization refers to the process of performing operations on entire arrays without the need for explicit loops in Python. This is achieved by leveraging optimized, low-level implementations in C, which are much faster than Python loops. For example, instead of using a loop to add two arrays element-wise, you can simply use the + operator:
# Example:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Vectorized addition
print ("Vectorized_addition:", c)

# Broadcasting:

# Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger one. This eliminates the need for manual replication of data and makes operations more memory-efficient.
# Example:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
c = a + b  # Broadcasting
print ("Broadcasted_addition:", c)

# Contribution to Efficiency:

# Speed: Both vectorization and broadcasting leverage optimized C code, which is much faster than Python loops12.
# Memory Efficiency: Broadcasting avoids unnecessary data replication, leading to more efficient memory usage2.
# Code Simplicity: These features make the code more concise and easier to read1.
# By using vectorization and broadcasting, we can write more efficient and readable code, which is crucial for handling large datasets and performing complex numerical computations.


Vectorized_addition: [5 7 9]
Broadcasted_addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
# Practical Questions & Answers:

In [ ]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

array = np.random.randint(1, 101, size=(3, 3))

transposed_array = array.T

print("Original array:")
print(array)
print("Transposed array:")
print(transposed_array)


Original array:
[[77 10 63]
 [42 13 96]
 [72 74 59]]
Transposed array:
[[77 42 72]
 [10 13 74]
 [63 96 59]]


In [ ]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

array_1d = np.arange(1, 11)  # This creates an array from 1 to 10

array_2x5 = array_1d.reshape((2, 5))

array_5x2 = array_2x5.reshape((5, 2))

print("Original 1D array:")
print(array_1d)
print("Reshaped to 2x5 array:")
print(array_2x5)
print("Reshaped to 5x2 array:")
print(array_5x2)


Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10]
Reshaped to 2x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reshaped to 5x2 array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

array_4x4 = np.random.rand(4, 4)

array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 array:")
print(array_4x4)
print("6x6 array with a border of zeros:")
print(array_6x6)


Original 4x4 array:
[[0.17496435 0.49980307 0.12371125 0.40559946]
 [0.72742933 0.79968578 0.91956092 0.34105915]
 [0.61209404 0.80732089 0.18153512 0.81901393]
 [0.27222235 0.51359055 0.52952707 0.39772451]]
6x6 array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.17496435 0.49980307 0.12371125 0.40559946 0.        ]
 [0.         0.72742933 0.79968578 0.91956092 0.34105915 0.        ]
 [0.         0.61209404 0.80732089 0.18153512 0.81901393 0.        ]
 [0.         0.27222235 0.51359055 0.52952707 0.39772451 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

array = np.arange(10, 65, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

array = np.array(['python', 'numpy', 'pandas'])

upper_case = np.char.upper(array)
lower_case = np.char.lower(array)
title_case = np.char.title(array)

print("Original array:")
print(array)
print("Uppercase transformation:")
print(upper_case)
print("Lowercase transformation:")
print(lower_case)
print("Title case transformation:")
print(title_case)


Original array:
['python' 'numpy' 'pandas']
Uppercase transformation:
['PYTHON' 'NUMPY' 'PANDAS']
Lowercase transformation:
['python' 'numpy' 'pandas']
Title case transformation:
['Python' 'Numpy' 'Pandas']


In [ ]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

words = np.array(['hello', 'world', 'numpy'])

spaced_words = np.char.join(' ', words)

print("Original array:")
print(words)
print("Array with spaces between each character:")
print(spaced_words)

Original array:
['hello' 'world' 'numpy']
Array with spaces between each character:
['h e l l o' 'w o r l d' 'n u m p y']


In [ ]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

addition = np.add(array1, array2)

subtraction = np.subtract(array1, array2)

multiplication = np.multiply(array1, array2)

division = np.divide(array1, array2)

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)


Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]
Element-wise addition:
[[ 6  8]
 [10 12]]
Element-wise subtraction:
[[-4 -4]
 [-4 -4]]
Element-wise multiplication:
[[ 5 12]
 [21 32]]
Element-wise division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

identity_matrix = np.identity(5)

diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity matrix:")
print(identity_matrix)
print("Diagonal elements:")
print(diagonal_elements)


5x5 Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements:
[1. 1. 1. 1. 1.]


In [ ]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

random_integers = np.random.randint(0, 1001, size=100)

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

primes = [num for num in random_integers if is_prime(num)]

print("Array of 100 random integers:")
print(random_integers)
print("Prime numbers in the array:")
print(primes)


Array of 100 random integers:
[237 447 136 873 558 521 989 482 928 438 594  93 937 307 636 509 547 951
 864 647 738 452 264 242 876 405 949 170 241 275 740 330 660 403 467 452
 199 699 968 179 500 267 150 718 905 270  30 667 508 147 455 988  55 146
 800 938 158 781 464 564 967 325 369 304 357  98 675 644 821 488 745 179
 897 998 243 886 802 846 155 951   4 286 561 962 139 554   0 205  83 810
 367 415 990  57 557 343 564 721 838 790]
Prime numbers in the array:
[521, 937, 307, 509, 547, 647, 241, 467, 199, 179, 967, 821, 179, 139, 83, 367, 557]


In [8]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

daily_temperatures = np.random.uniform(20, 30, 30)
print("Daily Temperatures:")
print(daily_temperatures)

weeks = np.array_split(daily_temperatures, 4)

weekly_averages = [np.mean(week) for week in weeks]
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures:
[21.70909585 23.58152167 27.50686141 26.07830669 23.25047229 20.38425426
 26.34274058 29.58949269 26.52790317 26.35058874 29.95299568 25.81850329
 24.14368588 24.74697502 26.23510101 23.38007615 26.74752322 23.17201742
 27.78345482 29.49571053 26.62526867 20.13571636 26.22846096 26.73659631
 29.71945002 28.78193471 25.09624377 20.55714694 24.51159215 20.19987665]

Weekly Averages:
[24.805343180128045, 25.894478617763774, 25.741164568448276, 25.086120078619754]
